### ISSUE TITLE
 failure in `sudo install.sh`

### ISSUE THREAD

**Issue by jeras** [antmicro/embench-tester#19]
The install step failed at `yosys`. Yosys recently tagged a new release, it might be related.

```
...
yosys-config --exec --cxx -c --cxxflags -o ghdl.o src/ghdl.cc -fPIC -DYOSYS_ENABLE_GHDL -I/usr/local/include -O
make: yosys-config: Command not found
make: *** [Makefile:24: ghdl.o] Error 127
```

**Comment by jeras** [comment]
I went through the new README.md instructions, and I did it on a different machine, both machines running Ubuntu 20.04.
I get the same error as before.

Also, could you add a note/warning regarding which programs are installed onto the system. I sometimes have specific versions installed on the system, and I would like to avoid some other tool installing a different version without a warning. Lately I prefer to just compile the program and add it to the PATH variable, to avoid modifying the system at all.

**Comment by mtdudek** [comment]
I think running install.sh without sudo should work now.
I've added to README what does install.sh modify/install

**Comment by pgielda** [comment]
Closing this stale issue.
