### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by cloudxcc** [antmicro/embench-tester#37]
I run 

make env
source env/conda/bin/activate embench-tester
./install.sh

and get the error below. 

snipset start

          __   _ __      _  __         
         / /  (_) /____ | |/_/         
        / /__/ / __/ -_)>  <           
       /____/_/\__/\__/_/|_|         
     Build your hardware, easily!      
          LiteX Setup utility.         

[   0.001] Initializing Git repositories...
[   0.001] --------------------------------
[   0.001] Cloning migen Git repository...
Cloning into 'migen'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "./litex_setup.py", line 448, in <module>
    main()
  File "./litex_setup.py", line 422, in main
    litex_setup_init_repos(config=args.config, tag=args.tag, dev_mode=args.dev)
  File "./litex_setup.py", line 216, in litex_setup_init_repos
    ), shell=True)
  File "/home/tobi/proj/Litex/git/embench-tester/env/conda/envs/embench-tester/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git clone git@github.com:m-labs/migen.git --recursive' returned non-zero exit status 128.

snipset end

I get the same error when running:

(embench-tester) tobi@x99:~/proj/Litex/git/embench-tester$ conda activate embench-tester

Any help highly appreciated. Sorry if this is a pathetic mistake on my side. Cheers.

**Comment by pgielda** [comment]
The problem lies here:

```
Cloning into 'migen'...
[git@github.com](mailto:git@github.com): Permission denied (publickey).
fatal: Could not read from remote repository.
```
Seems that you're trying to clone using git+ssh and the key is wrong.

Looking at the code it seems:
```
   if dev_mode:
                repo_url = repo_url.replace("https://github.com/", "git@github.com:")
```
that  there is a dev mode. And:
```
 litex_setup_init_repos(config=args.config, tag=args.tag, dev_mode=args.dev)
```
So it depends on args.dev:
```
 # Development mode.
    parser.add_argument("--dev", action="store_true", help="Development-Mode (no Auto-Update of litex_setup.py / Switch to git@github.com URLs).")
```
Looking at install.sh it uses this mode:
```
./litex_setup.py --init --install --user --dev --config full
```
@tmichalak is this --dev needed there?

In any case I suggest removing "--dev" and trying again.

**Comment by cloudxcc** [comment]
Excellent, removing --dev helps. Thanks.
