### ISSUE TITLE
What is these tests running on?

### ISSUE THREAD

**Issue by mithro** [antmicro/embench-tester#9]
I think they are running in Verilator?

How is the performance calculated then?

**Comment by kgugala** [comment]
Yes the tests are run in Verilator. Performance is calculated exactly the same way as it is done on HW - Embench scripts measure the execution time with a timer within the test SoC. The timer is simulated along with the rest of the system. We need to ensure that Embench is aware of the system clock frequency in the simulated SoC.

The tester uses a mechanism introduced in the Embench itself for the ri5ky CPU core (see: https://github.com/embench/embench-iot/tree/master/config/riscv32/boards/ri5cyverilator).
